-- MySQL Script generated by MySQL Workbench
-- Sat Jun  6 02:35:23 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema verdanatech
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema verdanatech
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `verdanatech` DEFAULT CHARACTER SET utf8 ;
USE `verdanatech` ;

-- -----------------------------------------------------
-- Table `verdanatech`.`tb_clients`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdanatech`.`tb_clients` (
  `id_clients` INT NOT NULL,
  `fantasy_name` VARCHAR(255) NOT NULL,
  `company_name` VARCHAR(255) NULL,
  `street` VARCHAR(50) NOT NULL,
  `number` VARCHAR(10) NOT NULL,
  `postal_code` VARCHAR(45) NOT NULL,
  `country` VARCHAR(45) NOT NULL,
  `type` TINYINT NOT NULL,
  `status` TINYINT NOT NULL,
  `city` VARCHAR(45) NOT NULL,
  `neighborhood` VARCHAR(45) NOT NULL,
  `state` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_clients`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `verdanatech`.`tb_type_product`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdanatech`.`tb_type_product` (
  `idtype` INT NOT NULL AUTO_INCREMENT,
  `type_name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idtype`))
ENGINE = MyISAM;


-- -----------------------------------------------------
-- Table `verdanatech`.`tb_produtos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `verdanatech`.`tb_produtos` (
  `idproduct` INT NOT NULL AUTO_INCREMENT,
  `name_product` VARCHAR(45) NOT NULL,
  `cost_price` DECIMAL(10,2) NOT NULL,
  `purchase_price` DECIMAL(10,2) NOT NULL,
  `purchase_date` DATE NULL,
  `id_clients` INT NOT NULL,
  `idtype` INT NOT NULL,
  PRIMARY KEY (`idproduct`, `id_clients`, `idtype`),
  INDEX `fk_tb_produtos_tb_clients_idx` (`id_clients` ASC),
  INDEX `fk_tb_produtos_tb_type_product1_idx` (`idtype` ASC))
ENGINE = MyISAM;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
